### ISSUE TITLE
Container does not start on reboot on Nostalgia

### ISSUE THREAD

**Issue by jamiereid** [makehackvoid/mhvdb2#91]
After a reboot, the container does not auto start. This means that someone is required to ssh in and manually start the container.

There should exist someway of making this automatic.

FYI I've enable the the Docker server to start at boot (as this too was disabled) using the update-rc.d command.

tl;dr: Find a way to have the container start on boot.

**Comment by brendam** [comment]
To manually start the container use:
'sudo make run' 
in the mhvdb2 main directory.

**Comment by jamiereid** [comment]
`nostalgia` is no longer the host of such things.
As we move towards using this again, we'll likely adapt it to the methods we currently use for docker containers on our servers.
