### ISSUE TITLE
What to do with bank related stuff?

### ISSUE THREAD

**Issue by brendam** [makehackvoid/mhvdb2#98]
Given that we've decided to go with GnuCash for payments, and payments are so separate from membership now I wonder if we should remove the initial code from this app that does banking stuff?

We might still want to implement stripe at some stage, but it wouldn't need to be part of this I think?

**Comment by jamiereid** [comment]
I agree with removing the code. We can always add it back later if we need
to.

**Comment by brendam** [comment]
I've started removing the 'payments' bits in a new branch. I think the 'entities' stuff can also go - it was for people who made payments that were not members.
What do you think @jamiereid and/or @cmrn?

**Comment by brendam** [comment]
Members are based on entities, so to remove entities we'd have to merge members and entities.
